In [2]:
text = []
with open("train.txt",encoding="utf8") as f: # โค้ดสำหรับเรียกไฟล์
    lines = f.readlines()
txt=[e.strip() for e in lines] # ใช้ลบช่องว่างของตัวอักษรแล้วนำมาใส่ไว้ใน listpos
f.close()
with open("train_label copy.txt",encoding="utf8") as f: # โค้ดสำหรับเรียกไฟล์
    lines = f.readlines()
train_posneg=[e.strip() for e in lines] # ใช้ลบช่องว่างของตัวอักษรแล้วนำมาใส่ไว้ใน listpos
f.close()

In [3]:
text_list = list(txt)
print(text_list)
#print(lines)

['เสียความรู้สึก', 'ช่างเลวจริงๆ', 'ผลงานย่ำแย่จนใกล้ตกชั้น', 'อึดอัดไม่รัก', 'ปวดหัวแท้ล้า', 'ขี้เกียจล้านตัว', 'อำลานี้ไม่เจออีกน่ะ', 'เวลาเหนื่อยนี่บ่นใครบ้าง', 'นกบ่อยขนาดนี้ควรไปตายเกิดใหม่เถอะ', 'ไม่ต่างสัตว์เดรัจฉาน', 'หยังอายคิดอาย', 'เพ้อเจ้อกคิดไปเอง มโนไปเอง', 'ถูกทัณฑ์ทรนแห่งนรก', 'ข่มขู่บีบบังคับ', 'เดี่ยวเสียทีหลัง', 'เธอมองข้าม', 'นี้ไงถึงไม่อยากให้รู้เพราะว่าวุ่นวายเเค่นี้กพอเเล้ว', 'หลอกให้รัก', 'อยู่ใกล้เอื้อไม่ไปหาไม่', 'สวยไงขนาดครีมยังขี้เกียจทา', 'เมื่อยๆๆร่างกายอ่อนเพลีย', 'เรื่องนี้บางครั้งมันเกินขอบเขตของคำว่าพอเกินไป', 'ว่างไม่อะไรทำ', 'ไม่สร้างสรรค์', 'สนุกบนความทุกข์ความไม่สบายของอื่น', 'ราคาแพงเกินไปไม่คุ้ม', 'ทรณการเมินใส่เเต่ไม่บอกเลิก', 'ชอบขี้งอนและน้อย', 'มันรู้สึกเหนื่อยจนไม่รู้ว่าระบายออกยังไง', 'ฟุ้งซ่าน', 'หิวกขี้เกียจลุกไปกิน', 'เครียดปวดหัว', 'มันเจ็บๆหัวว่ะ', 'ล้มโดนเหยียบซ้ำโดนนินทาสารพัดผิดไปหมด', 'เสือกสอบไม่ติด', 'กูโง่ขนาดนั้นหรอ', 'สอบไม่ติดเสียดาย', 'โดดเดี่ยวไม่มีใคร', 'อันตรายกกว่าคิด', 'ร้องไห้เสียการลาจาก', 'ฆ่าตัวตายจากปัญหาความเครีย

In [4]:
import re
import string

def clean_msg(msg):
    
    
    # ลบ text ที่อยู่ในวงเล็บ <> ทั้งหมด
    msg = re.sub(r'<.*?>','', msg)
    
    # ลบ hashtag
    msg = re.sub(r'#','',msg)
    
    # ลบ …
    msg = re.sub(r'…','',msg)
    
    # ลบ เครื่องหมายคำพูด (punctuation)
    for c in string.punctuation:
        msg = re.sub(r'\{}'.format(c),'',msg)
    
    # ลบ separator เช่น \n \t
    msg = ' '.join(msg.split())
    
    return msg

In [5]:
print('original text:\n',text_list[0])
print('clean text:\n',clean_msg(text_list[0]))

original text:
 เสียความรู้สึก
clean text:
 เสียความรู้สึก


In [6]:
print('original text:\n',text_list[1])
print('clean text:\n',clean_msg(text_list[1]))

original text:
 ช่างเลวจริงๆ
clean text:
 ช่างเลวจริงๆ


In [7]:
clean_text = [clean_msg(txt) for txt in text_list]

In [8]:
#!pip install pythainlp
#!pip install stop_words
import pythainlp
from pythainlp import word_tokenize
from pythainlp.corpus import thai_stopwords
from pythainlp.corpus import wordnet
from nltk.stem.porter import PorterStemmer
from nltk.corpus import words
from stop_words import get_stop_words

In [9]:
import nltk
nltk.download('words')
th_stop = tuple(thai_stopwords())
en_stop = tuple(get_stop_words('en'))
p_stemmer = PorterStemmer()

#print(th_stop)

[nltk_data] Downloading package words to
[nltk_data]     C:\Users\Seena\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


In [10]:
def split_word(text):
            
    
    tokens = word_tokenize(text,engine='newmm')
    
    # Remove stop words ภาษาไทย และภาษาอังกฤษ
    tokens = [i for i in tokens if not i in th_stop and not i in en_stop]
    #tokens = [i for i in tokens ]
    
    # หารากศัพท์ภาษาไทย และภาษาอังกฤษ
    # English
    tokens = [p_stemmer.stem(i) for i in tokens]
    
    # Thai
    tokens_temp=[]
    for i in tokens:
        w_syn = wordnet.synsets(i)
        if (len(w_syn)>0) and (len(w_syn[0].lemma_names('tha'))>0):
            tokens_temp.append(w_syn[0].lemma_names('tha')[0])
        else:
            tokens_temp.append(i)
    
    tokens = tokens_temp
    
    # ลบตัวเลข
    tokens = [i for i in tokens if not i.isnumeric()]
    
    # ลบช่องว่าง
    tokens = [i for i in tokens if not ' ' in i]

    return tokens

In [11]:
print('tokenized text:\n',split_word(clean_msg(text_list[0])))
print('tokenized text:\n',split_word(clean_msg(text_list[1])))
print('tokenized text:\n',split_word(clean_msg(text_list[2])))
print('tokenized text:\n',split_word(clean_msg(text_list[3])))
print('tokenized text:\n',split_word(clean_msg(text_list[4])))
print('tokenized text:\n',split_word(clean_msg(text_list[5])))
print('tokenized text:\n',split_word(clean_msg(text_list[6])))
print('tokenized text:\n',split_word(clean_msg(text_list[7])))
print('tokenized text:\n',split_word(clean_msg(text_list[8])))
print('tokenized text:\n',split_word(clean_msg(text_list[9])))

tokenized text:
 ['เสียความรู้สึก']
tokenized text:
 ['ช่าง', 'เลว']
tokenized text:
 ['งาน', 'ย่ำแย่', 'ตก', 'ชั้น']
tokenized text:
 ['อึดอัด', 'รัก']
tokenized text:
 ['ปวดหัว', 'ล้า']
tokenized text:
 ['ขี้เกียจ', 'ล้าน', 'ตัว']
tokenized text:
 ['อำลา', 'เจอ']
tokenized text:
 ['กาล', 'เหนื่อย', 'บ่น']
tokenized text:
 ['นก', 'ขนาด', 'ตาย']
tokenized text:
 ['สัตว์เดรัจฉาน']


In [12]:
tokens_list = [split_word(txt) for txt in clean_text]

In [13]:
tokens_list

[['เสียความรู้สึก'],
 ['ช่าง', 'เลว'],
 ['งาน', 'ย่ำแย่', 'ตก', 'ชั้น'],
 ['อึดอัด', 'รัก'],
 ['ปวดหัว', 'ล้า'],
 ['ขี้เกียจ', 'ล้าน', 'ตัว'],
 ['อำลา', 'เจอ'],
 ['กาล', 'เหนื่อย', 'บ่น'],
 ['นก', 'ขนาด', 'ตาย'],
 ['สัตว์เดรัจฉาน'],
 ['หยัง', 'อาย', 'อาย'],
 ['เพ้อ', 'เจ้', 'อก', 'มโน'],
 ['ทัณฑ์', 'ทร', 'น', 'นรก'],
 ['ข่มขู่', 'บีบ'],
 ['โซโล่', 'ทีหลัง'],
 ['มองข้าม'],
 ['รู้', 'วุ่นวาย', 'เเค่', 'กพอเเล้ว'],
 ['หลอก', 'รัก'],
 ['เอื้อ', 'หาไม่'],
 ['สวย', 'ขนาด', 'ครีม', 'ขี้เกียจ', 'ทา'],
 ['เมื่อย', 'ๆๆ', 'ตัว', 'อ่อนเพลีย'],
 ['เรื่อง', 'เกินขอบเขต', 'เกิน'],
 ['ว่าง', 'ทำ'],
 ['สร้างสรรค์'],
 ['ชอบ', 'ความทุกข์', 'ไม่สบาย'],
 ['ราคาแพง', 'เกิน', 'คุ้ม'],
 ['ทร', 'เมิน', 'ใส่', 'เเต่', 'บอกเลิก'],
 ['ชอบ', 'ขี้งอน'],
 ['รู้สึก', 'เหนื่อย', 'ไม่รู้', 'ระบาย'],
 ['ฟุ้งซ่าน'],
 ['หิว', 'ก', 'ขี้เกียจ', 'ลุก', 'กิน'],
 ['เครียด', 'ปวดหัว'],
 ['ปวด', 'หัว', 'ว่ะ'],
 ['ล้ม', 'โดน', 'เหยียบ', 'ซ้ำ', 'โดน', 'นินทา', 'สารพัด'],
 ['เสือก', 'สอบ', 'ติด'],
 ['โง่', 'ขนาด', 'หรอ'],
 ['สอบ', 

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
tokens_list_j = [','.join(tkn) for tkn in tokens_list]
cvec = CountVectorizer(analyzer=lambda x:x.split(','))
c_feat = cvec.fit_transform(tokens_list_j)

In [15]:
vocab = cvec.vocabulary_
print(vocab)
#print(tokens_list_j)

{'เสียความรู้สึก': 511, 'ช่าง': 111, 'เลว': 505, 'งาน': 84, 'ย่ำแย่': 288, 'ตก': 131, 'ชั้น': 104, 'อึดอัด': 439, 'รัก': 298, 'ปวดหัว': 226, 'ล้า': 328, 'ขี้เกียจ': 35, 'ล้าน': 329, 'ตัว': 139, 'อำลา': 435, 'เจอ': 462, 'กาล': 17, 'เหนื่อย': 518, 'บ่น': 210, 'นก': 182, 'ขนาด': 22, 'ตาย': 144, 'สัตว์เดรัจฉาน': 366, 'หยัง': 399, 'อาย': 434, 'เพ้อ': 493, 'เจ้': 464, 'อก': 418, 'มโน': 279, 'ทัณฑ์': 157, 'ทร': 155, 'น': 181, 'นรก': 183, 'ข่มขู่': 37, 'บีบ': 209, 'โซโล่': 559, 'ทีหลัง': 169, 'มองข้าม': 267, 'รู้': 306, 'วุ่นวาย': 336, 'เเค่': 530, 'กพอเเล้ว': 3, 'หลอก': 404, 'เอื้อ': 529, 'หาไม่': 413, 'สวย': 359, 'ครีม': 44, 'ทา': 159, 'เมื่อย': 497, 'ๆๆ': 601, 'อ่อนเพลีย': 441, 'เรื่อง': 503, 'เกินขอบเขต': 451, 'เกิน': 450, 'ว่าง': 338, 'ทำ': 161, 'สร้างสรรค์': 357, 'ชอบ': 101, 'ความทุกข์': 52, 'ไม่สบาย': 591, 'ราคาแพง': 301, 'คุ้ม': 76, 'เมิน': 495, 'ใส่': 574, 'เเต่': 531, 'บอกเลิก': 206, 'ขี้งอน': 33, 'รู้สึก': 309, 'ไม่รู้': 588, 'ระบาย': 295, 'ฟุ้งซ่าน': 260, 'หิว': 415, 'ก': 1, 'ลุก':

In [16]:
c_feat[:,:20].todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(analyzer=lambda x:x.split(','),)
t_feat = tvec.fit_transform(tokens_list_j)

In [18]:
t_feat[:,:5].todense()

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
print(len(tvec.idf_),len(tvec.vocabulary_))

602 602


In [20]:
c_feat[:,:5].todense()

matrix([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        ...,
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=int64)

In [21]:
print(c_feat.todense())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [22]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB

In [23]:
X = np.array(c_feat.todense())

In [24]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
 y = np.array(train_posneg)

In [26]:
clf = MultinomialNB(class_prior=[0.25, 0.5])

# Train model
model = clf.fit(X, y)

In [27]:
print(model)

MultinomialNB(class_prior=[0.25, 0.5])


In [28]:
# Create new observation
new_observation = [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [29]:
# Predict new observation's class
y_predicted = model.predict(X)

In [31]:
# save the data to disk
#data = 'y_predicted.pkl'
#pickle.dump(y_predicted, open(data, 'wb'))

In [305]:
print(y_predicted)

['-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-' '-'
 '-' '-' '-' '-' '-' '-' '-' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+'
 '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+'
 '+' '+' '+' '+' '-' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+'
 '+' '-' '-' '+' '+' '+' '+' '+' '+' '+' '+' '+' '+' '-' '+' '+' '+' '+'
 '+' '+' '+' '+' '+' '+' '+' '-' '-' '+' '+' '+' '+